### PR TITLE
revert external LB example

### PR DESCRIPTION
**Pull request by rosemarymarano**
Reverted External Load Balancers example to its version in the 1.3 docs, as per [VZ-8259](https://jira.oraclecorp.com/jira/browse/VZ-8259) Correct External Load Balancers example in our docs

### CODE REVIEW

**Comment by guoyongzhang** [comment]
I think we do want v1beta1.  I will supply an example when I get a chance.

**Comment by guoyongzhang** [comment]
It turns out the only change needed for the original v1.4 example is to replace `ingress` with `ingressNGINX`.

**Review by guoyongzhang — APPROVED** [review]
Perfect

**Comment by guoyongzhang** [comment]
I am sure you will backport to 1.4 as well

**Comment by rosemarymarano** [comment]
Yes, I will.

**Pull request merged**
