### PR TITLE
Alyslevi/vz 7301

### PR DESCRIPTION
**Pull request by alyssavlev**
Buttons added to each page, excluding pages with "tab" functionality. So added to all pages but: 

Sockshop
Setup > Use a Private Registary 
Access Verrazzano
Customize VZ -> DNS
Upgrade, Backup and Uninstall -> upgrade

I will get back to these pages later, the issue is due to my CSS in a head tag, as a header is already in the rendered HTML that Hugo generates. This copy button matches the same color as the top of the page (same hex code) and will change from saying copy to copied once copied to clipboard.

### CODE REVIEW

**Review by AbeHern — APPROVED** [review]
LGTM!

**Review by MelwynPaul — COMMENTED** [review]
A few comments...

Comment # 1
Global comment (all tags): 
When we hit copy, The $ sign is not copied. This is awesome!
However, can we also exclude the (space) after the $ symbol?
That is, when copying, it should exclude $(space)


Comment # 2
Global comment (all tags): 
We see that every codeblock is copied with a ‘return’ at the end/bottom. 
(This is not the case in a manual copy-paste.) 
Is this intentional to assist the users? 
(not always useful) 


Comment # 3
In yaml or java codeblock tags/types, we see extra break lines after each line of code: 
(This is not the case in a manual copy-paste.) 
Examples: 
1 - yaml tag: Customize Verrazzano > OCI Load Balancers
2 - java tag: Guides > Application Deployment

Comment # 4
Pages missed--
1 – Pages with tabs (not in your ‘later’ list - so including in case these are missed)
    a)	Upgrade, Backup and Uninstall > Uninstall
    b)	Setup > Install  > Install Guide

2 – These are regular pages (no tabs)
Upgrade, Back Up, & Uninstall > Back Up and Restore > (all 3 topics) 
These are new topics but merged. So, the button is not yet added.

3 - No Copy button for codeblock in table cells?
Example: Customize Verrazzano > AuthProxy 
However, AFAIK this is the only instance where we have codeblock in a table.

4 - FYI. 
The topic “Access Verrazzano” is included in your 'later' list.
On this page, I see the Copy button for the codeblock in tabs.

Thank you.

**Review by MelwynPaul — COMMENTED** [review]
@alyssavlev 
Thanks a lot for fixing all the comments. 
I have one more comment and an observation. 
------------------

Round # 2

Comment # 1 - Missed 
1 - _Page_: Security > Application Security
2 - _Table_: Customize Verrazzano > Istio


Comment # 2 
Observation ---  

In a couple of instances, I see that the "sample output" which is in the same block as the command does **not** get copied.  
Example: Setup > Install > Install Guide (kubectl tab)

Whereas, in all other instances the "sample output" content (which is in the same block as the command) gets copied to the clipboard. 

Is this something you planned? 

I am okay with/without copying the "sample output" content. 
However, as I observed this in a couple of instances, I think it is particularly useful in blocks where the "sample output" content is more than the command.
Like in: Customize Verrazzano > OpenSearch (2nd block)

Thank you.

**Comment by rosemarymarano** [comment]
@alyssavlev @MelwynPaul Regarding Comment # 2 in Melwyn's review: whether the "sample output" content should be copied. 
I think that it definitely should **not** be copied, in any instance. (Feel free to review this point of view with other developers.)
The point of copying the command is for developers to easily copy commands from the doc and paste them directly into their terminal window. What point is there to copying the sample output? If you want that behavior, please clarify it for me.

**Review by rosemarymarano — APPROVED** [review]
LGTM. After @MelwynPaul approves, you can merge the changes.

**Pull request merged**
